primary:
- config/drivetrain.yaml
- config/elevator.yaml
override:
  ferb:
  - config/ferb/ferb-drivetrain.yaml
  - config/ferb/ferb-elevator.yaml
  pandora:
  - config/pandora/pandora-drivetrain.yaml
  - config/pandora/pandora-elevator.yaml
